### ISSUE TITLE
Set gmsh logging level

### ISSUE THREAD

**Issue by dbrakenhoff** [Deltares/pandamesh#7]
Is it possible to modify the code so the gmsh log level can be set? For a small example notebook, I don't want to show the gmsh logging output, e.g. `gmsh.option.setNumber("General.Verbosity", 0)`

Also, the gmsh.finalize() call is causing an `Error   : Gmsh has not been initialized` to show up in the output on my machine.

**Comment by Huite** [comment]
Hi @dbrakenhoff,

I just pushed f5372c7873069adfbcb476e3646b8afeb27bdbc1 which adds a GeneralVerbosity Enum, and the constructor now sets it to silent by default.

Regarding the gmsh error, are you referring to the call in the `_initialize_gmsh` method?
https://github.com/Deltares/pandamesh/blob/2e91933092abce7ac94e97ec8e26ead2e975213f/pandamesh/gmsh_mesher.py#L195

In that case, the error is expected (and it's harmless, right?).
I do not remember very clearly, but I think I had to try-expect this because calling initialize twice was not harmless.

**Comment by dbrakenhoff** [comment]
Thanks for the improvements! 

I think you're right about the harmless message. I figured I'd mention it because this harmless message has disguised itself by starting with "Error", which could be somewhat confusing for users :).

**Comment by remi-braun** [comment]
Hello,

Is this log correction released yet? 😄 
If not, when do you plan to do it?

**Comment by Huite** [comment]
Hi @remi-braun,

It's not released on pypi or conda-forge yet; I had in mind to investigate the gmsh finalize error message Davíd reported a little further. But other things kept me busy!

I'll move it up in my to do list (maybe it's a nice Friday afternoon task) since you're asking! ^^

**Comment by remi-braun** [comment]
Thanks a lot!
